%define INSTANCE /opt/zope
%define CLIENT_HOME /opt/zope/var
%define ZODB_CACHE_SIZE 50000

instancehome $INSTANCE
clienthome $CLIENT_HOME

debug-mode DEBUG_MODE_MARKER
security-policy-implementation python
verbose-security VERBOSE_SECURITY_MARKER
default-zpublisher-encoding utf-8

%include $INSTANCE/etc/zodb.conf
